'use server';

/**
 * @fileOverview Generates detailed, structured explanations in 'Pro' mode for interview answers.
 *
 * - generateDetailedAnswer - A function that generates detailed answers based on the input and context.
 * - GenerateDetailedAnswerInput - The input type for the generateDetailedAnswer function.
 * - GenerateDetailedAnswerOutput - The return type for the generateDetailedAnswer function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateDetailedAnswerInputSchema = z.object({
  question: z.string().describe('The interview question asked by the interviewer.'),
  userContext: z.object({
    resume: z.string().describe('The user\'s resume content.'),
    speakingStyle: z.string().describe('The user\'s preferred speaking style.'),
  }).describe('The user context including resume and speaking style.'),
  jobContext: z.object({
    companyName: z.string().describe('The name of the company.'),
    jobDescription: z.string().describe('The job description for the role.'),
  }).describe('The job context including company name and job description.'),
});
export type GenerateDetailedAnswerInput = z.infer<typeof GenerateDetailedAnswerInputSchema>;

const GenerateDetailedAnswerOutputSchema = z.object({
  answer: z.string().describe('The detailed and structured answer generated by the AI.'),
});
export type GenerateDetailedAnswerOutput = z.infer<typeof GenerateDetailedAnswerOutputSchema>;

export async function generateDetailedAnswer(input: GenerateDetailedAnswerInput): Promise<GenerateDetailedAnswerOutput> {
  return generateDetailedAnswersFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateDetailedAnswerPrompt',
  input: {schema: GenerateDetailedAnswerInputSchema},
  output: {schema: GenerateDetailedAnswerOutputSchema},
  prompt: `You are an AI assistant designed to help users answer interview questions in a detailed and structured manner.

You have access to the user's resume, speaking style, and the job description for the role they are interviewing for.

User Resume: {{{userContext.resume}}}

User Speaking Style: {{{userContext.speakingStyle}}}

Job Description: {{{jobContext.jobDescription}}}

Based on this information, please provide a comprehensive and well-organized answer to the following interview question:

Question: {{{question}}}

Your answer should be structured, detailed, and tailored to the user's background and the specific job requirements.`,
});

export const generateDetailedAnswersFlow = ai.defineFlow(
  {
    name: 'generateDetailedAnswersFlow',
    inputSchema: GenerateDetailedAnswerInputSchema,
    outputSchema: GenerateDetailedAnswerOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
